# Generated by Django 4.2.6 on 2023-11-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='p_contract',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='p_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='p_facebook',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='p_line',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='p_telephone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='p_worktear',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_lastname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='p_picture',
            field=models.ImageField(null=True, upload_to='proflie_pictures/'),
        ),
    ]
